// Generated by CoffeeScript 2.5.1
(function() {
  var Modules;

  Modules = {
    cliargumentsmodule: require("./cliargumentsmodule"),
    debugmodule: require("./debugmodule"),
    genservicefilesprocessmodule: require("./genservicefilesprocessmodule"),
    servicefilegenmodule: require("./servicefilegenmodule"),
    startupmodule: require("./startupmodule"),
    pathhandlermodule: require("./pathhandlermodule")
  };

  module.exports = Modules;

}).call(this);
